### ISSUE TITLE
Download data not working

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#39]
When I select "Download Data" I'm prompted where to save the data, but it doesn't appear to actually download. Can't find file.

**Comment by mplourde** [comment]
Fixed in upcoming release.

**Comment by edwardlennonjr** [comment]
I'm still having the same issue. The filename is surrounded by quotes, unsure if that's why?
